version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task-manager
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always

  task-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-container
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: mysql://user:userpassword@mysql:3306/task-manager
      REDIS_URL: redis://redis:6379
      PORT: 3000
    restart: always

volumes:
  mysql-data:
    driver: local
